#!/bin/bash

# cleanup the data generated by running
#   `rake benchmark:big_row | ./clean_data.sh -`

cat $1 | tail -n+3 | awk '{ gsub(/\(|\)/, "") } $1=$1' | awk '{ gsub(/^ */, " ") } $1=$1' | awk '{ print $1, ",", $5 }'
